server:
  port: 8081
  tomcat:
    threads.max: 50
    max-connections: 100
    max-http-form-post-size: 120MB
    connection-timeout: 60000

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.qq.com
    username: 1349452816@qq.com
    password: ehooplasmsmsbafh
    default-encoding: utf-8
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://14.103.49.81:33060/poetize?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: ^tPT4DwgTX9cKyOm

store:
  type: qiniu

local:
  enable: false
  uploadUrl: ./file/
  downloadUrl: v

qiniu:
  enable: true
  accessKey: "uUqVMihs8hW4d_zl3IwVGZVkLyffEqhDZ8ENocBB"
  secretKey: "NtmhnqOA90fSaMDZMjjx9JG8fWHKptxNE5U14Evc"
  bucket: "dabaibai-blog"
  downloadUrl: "http://s95qk8pho.hn-bkt.clouddn.com/"